# Generated by Django 4.1.7 on 2023-06-21 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outfitGenerator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shoes',
            new_name='Shoe',
        ),
    ]
