# Generated by Django 4.1.7 on 2023-06-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfitGenerator', '0002_rename_shoes_shoe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottomclothing',
            name='type',
            field=models.CharField(choices=[('J', 'Jeans'), ('DP', 'Dress Pants'), ('SP', 'Sweatpants')], default='J', max_length=2),
        ),
    ]
