# Generated by Django 4.1.7 on 2023-07-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfitGenerator', '0004_bottomclothing_user_shoe_user_topclothing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottomclothing',
            name='colour',
            field=models.CharField(choices=[('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Yellow-Green', 'Yellow-Green'), ('Green', 'Green'), ('Blue-Green', 'Blue-Green'), ('Blue', 'Blue'), ('Blue-Violet', 'Blue-Violet'), ('Violet', 'Violet'), ('Mauve', 'Mauve'), ('Mauve-Pink', 'Mauve-Pink'), ('Pink', 'Pink'), ('Black', 'Black'), ('White', 'white'), ('Grey', 'Grey')], default='Red', max_length=15),
        ),
        migrations.AlterField(
            model_name='bottomclothing',
            name='type',
            field=models.CharField(choices=[('Jeans', 'Jeans'), ('Dress Pants', 'Dress Pants'), ('Sweatpants', 'Sweatpants')], default='Jeans', max_length=15),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='colour',
            field=models.CharField(choices=[('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Yellow-Green', 'Yellow-Green'), ('Green', 'Green'), ('Blue-Green', 'Blue-Green'), ('Blue', 'Blue'), ('Blue-Violet', 'Blue-Violet'), ('Violet', 'Violet'), ('Mauve', 'Mauve'), ('Mauve-Pink', 'Mauve-Pink'), ('Pink', 'Pink'), ('Black', 'Black'), ('White', 'white'), ('Grey', 'Grey')], default='Red', max_length=15),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='type',
            field=models.CharField(choices=[('Sneakers', 'Sneakers'), ('Dress Shoes', 'Dress Shoes'), ('Running Shoes', 'Running Shoes')], default='Sneakers', max_length=15),
        ),
        migrations.AlterField(
            model_name='topclothing',
            name='colour',
            field=models.CharField(choices=[('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Yellow-Green', 'Yellow-Green'), ('Green', 'Green'), ('Blue-Green', 'Blue-Green'), ('Blue', 'Blue'), ('Blue-Violet', 'Blue-Violet'), ('Violet', 'Violet'), ('Mauve', 'Mauve'), ('Mauve-Pink', 'Mauve-Pink'), ('Pink', 'Pink'), ('Black', 'Black'), ('White', 'white'), ('Grey', 'Grey')], default='Red', max_length=15),
        ),
        migrations.AlterField(
            model_name='topclothing',
            name='type',
            field=models.CharField(choices=[('T-Shirt', 'T-Shirt'), ('Dress Shirt', 'Dress Shirt'), ('Jacket', 'Jacket')], default='T-Shirt', max_length=15),
        ),
    ]
