# Generated by Django 4.2.4 on 2023-09-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "outfitGenerator",
            "0008_alter_bottomclothing_colour_alter_shoe_colour_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="topclothing",
            name="type",
            field=models.CharField(
                choices=[
                    ("T-Shirt", "T-Shirt"),
                    ("Dress Shirt", "Dress Shirt"),
                    ("Hoodie", "Hoodie"),
                ],
                default="T-Shirt",
                max_length=15,
            ),
        ),
    ]
