# Generated by Django 4.2.4 on 2023-09-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "outfitGenerator",
            "0011_alter_bottomclothing_colour_alter_shoe_colour_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bottomclothing",
            name="colour",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="shoe",
            name="colour",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="topclothing",
            name="colour",
            field=models.CharField(max_length=15),
        ),
    ]
