# Generated by Django 4.2.1 on 2023-09-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfitGenerator', '0015_bottomclothing_saturation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottomclothing',
            name='colour',
            field=models.CharField(choices=[('#FF0000', 'Red'), ('#FF5349', 'Red-Orange'), ('#FFA500', 'Orange'), ('#F5BD1F', 'Yellow-Orange'), ('#FFFF00', 'Yellow'), ('#9ACD32', 'Yellow-Green'), ('#00FF00', 'Green'), ('#0D98BA', 'Blue-Green'), ('#0000FF', 'Blue'), ('#8A2BE2', 'Blue-Violet'), ('#7F00FF', 'Violet'), ('#922B3E', 'Red-Violet'), ('#242526', 'Black'), ('#F7F5F0', 'White'), ('#808080', 'Grey'), ('#964B00', 'Brown')], default='#FF0000', max_length=17),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='colour',
            field=models.CharField(choices=[('#FF0000', 'Red'), ('#FF5349', 'Red-Orange'), ('#FFA500', 'Orange'), ('#F5BD1F', 'Yellow-Orange'), ('#FFFF00', 'Yellow'), ('#9ACD32', 'Yellow-Green'), ('#00FF00', 'Green'), ('#0D98BA', 'Blue-Green'), ('#0000FF', 'Blue'), ('#8A2BE2', 'Blue-Violet'), ('#7F00FF', 'Violet'), ('#922B3E', 'Red-Violet'), ('#242526', 'Black'), ('#F7F5F0', 'White'), ('#808080', 'Grey'), ('#964B00', 'Brown')], default='#FF0000', max_length=17),
        ),
        migrations.AlterField(
            model_name='topclothing',
            name='colour',
            field=models.CharField(choices=[('#FF0000', 'Red'), ('#FF5349', 'Red-Orange'), ('#FFA500', 'Orange'), ('#F5BD1F', 'Yellow-Orange'), ('#FFFF00', 'Yellow'), ('#9ACD32', 'Yellow-Green'), ('#00FF00', 'Green'), ('#0D98BA', 'Blue-Green'), ('#0000FF', 'Blue'), ('#8A2BE2', 'Blue-Violet'), ('#7F00FF', 'Violet'), ('#922B3E', 'Red-Violet'), ('#242526', 'Black'), ('#F7F5F0', 'White'), ('#808080', 'Grey'), ('#964B00', 'Brown')], default='#FF0000', max_length=17),
        ),
    ]
