# Generated by Django 4.2.4 on 2024-01-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "outfitGenerator",
            "0017_alter_bottomclothing_colour_alter_shoe_colour_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bottomclothing",
            name="formality",
            field=models.CharField(
                choices=[
                    ("Casual", "Casual"),
                    ("Smart-Casual", "Smart-Casual"),
                    ("Either", "Either"),
                ],
                default="NULL",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="shoe",
            name="formality",
            field=models.CharField(
                choices=[
                    ("Casual", "Casual"),
                    ("Smart-Casual", "Smart-Casual"),
                    ("Either", "Either"),
                ],
                default="NULL",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="topclothing",
            name="formality",
            field=models.CharField(
                choices=[
                    ("Casual", "Casual"),
                    ("Smart-Casual", "Smart-Casual"),
                    ("Either", "Either"),
                ],
                default="NULL",
                max_length=12,
            ),
        ),
    ]
