# Generated by Django 4.2.4 on 2024-01-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outfitGenerator", "0019_alter_shoe_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bottomclothing",
            name="formality",
            field=models.CharField(
                choices=[
                    ("Casual", "Casual"),
                    ("Smart-Casual", "Smart-Casual"),
                    ("Either", "Either"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="shoe",
            name="formality",
            field=models.CharField(
                choices=[
                    ("Casual", "Casual"),
                    ("Smart-Casual", "Smart-Casual"),
                    ("Either", "Either"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="topclothing",
            name="formality",
            field=models.CharField(
                choices=[
                    ("Casual", "Casual"),
                    ("Smart-Casual", "Smart-Casual"),
                    ("Either", "Either"),
                ],
                max_length=12,
            ),
        ),
    ]
