# Generated by Django 4.2.4 on 2024-01-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "outfitGenerator",
            "0020_alter_bottomclothing_formality_alter_shoe_formality_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bottomclothing",
            name="type",
            field=models.CharField(
                choices=[
                    ("jeans", "Jeans"),
                    ("dress_pants", "Dress Pants"),
                    ("sweatpants", "Sweatpants"),
                ],
                default="jeans",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="shoe",
            name="type",
            field=models.CharField(
                choices=[
                    ("sport_sneakers", "Sport Sneakers"),
                    ("dress_shoes", "Dress Shoes"),
                ],
                default="sport_sneakers",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="topclothing",
            name="type",
            field=models.CharField(
                choices=[
                    ("tshirt", "T-Shirt"),
                    ("dress_shirt", "Dress Shirt"),
                    ("hoodie", "Hoodie"),
                    ("formal_jacket", "Formal Jacket"),
                    ("varsity", "Varsity Jacket"),
                ],
                default="tshirt",
                max_length=15,
            ),
        ),
    ]
